//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiplicationTable.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiplicationTable.Resx.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update settings.
        /// </summary>
        public static string btnAboutUpdate {
            get {
                return ResourceManager.GetString("btnAboutUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string btnAnswer {
            get {
                return ResourceManager.GetString("btnAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string btnCheck {
            get {
                return ResourceManager.GetString("btnCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint.
        /// </summary>
        public static string btnHint {
            get {
                return ResourceManager.GetString("btnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load user defined dictations.
        /// </summary>
        public static string btnLoadUserDefinedDict {
            get {
                return ResourceManager.GetString("btnLoadUserDefinedDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load user defined words.
        /// </summary>
        public static string btnLoadUserDefinedWords {
            get {
                return ResourceManager.GetString("btnLoadUserDefinedWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload and overwrite user defined dictations.
        /// </summary>
        public static string btnSaveUserDefinedDict {
            get {
                return ResourceManager.GetString("btnSaveUserDefinedDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload and overwrite user defined words.
        /// </summary>
        public static string btnSaveUserDefinedWords {
            get {
                return ResourceManager.GetString("btnSaveUserDefinedWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say it.
        /// </summary>
        public static string btnSay {
            get {
                return ResourceManager.GetString("btnSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        public static string btnShuffle {
            get {
                return ResourceManager.GetString("btnShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string btnTest {
            get {
                return ResourceManager.GetString("btnTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string pckAboutText {
            get {
                return ResourceManager.GetString("pckAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition part max value.
        /// </summary>
        public static string txtAboutAddMax {
            get {
                return ResourceManager.GetString("txtAboutAddMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple app for learning basics in maths, learning words (PL-EN), dictations (sample texts taken from szkolnictwo.pl website).
        /// </summary>
        public static string txtAboutApp {
            get {
                return ResourceManager.GetString("txtAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About author (github).
        /// </summary>
        public static string txtAboutGithub {
            get {
                return ResourceManager.GetString("txtAboutGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication part max value.
        /// </summary>
        public static string txtAboutMultMax {
            get {
                return ResourceManager.GetString("txtAboutMultMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz mode?.
        /// </summary>
        public static string txtAboutQuizMode {
            get {
                return ResourceManager.GetString("txtAboutQuizMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This simple app is for learning simple math operations, polish word exceptions and english words. App is written using Xamarin platform.
        /// </summary>
        public static string txtAboutSpan {
            get {
                return ResourceManager.GetString("txtAboutSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtraction part max value.
        /// </summary>
        public static string txtAboutSubMax {
            get {
                return ResourceManager.GetString("txtAboutSubMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string txtAboutTimeout {
            get {
                return ResourceManager.GetString("txtAboutTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAD.
        /// </summary>
        public static string txtDictBad {
            get {
                return ResourceManager.GetString("txtDictBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all answers selected.
        /// </summary>
        public static string txtDictErrorNotAllAnsweres {
            get {
                return ResourceManager.GetString("txtDictErrorNotAllAnsweres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer all questions.
        /// </summary>
        public static string txtDictErrorNotAllAnswersTitle {
            get {
                return ResourceManager.GetString("txtDictErrorNotAllAnswersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string txtDictOk {
            get {
                return ResourceManager.GetString("txtDictOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hurra!!!.
        /// </summary>
        public static string txtDictSuccessMesssage {
            get {
                return ResourceManager.GetString("txtDictSuccessMesssage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRAVO.
        /// </summary>
        public static string txtDictSuccessTitle {
            get {
                return ResourceManager.GetString("txtDictSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUM.
        /// </summary>
        public static string txtDictSum {
            get {
                return ResourceManager.GetString("txtDictSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading user data.
        /// </summary>
        public static string txtErrLoadingUserData {
            get {
                return ResourceManager.GetString("txtErrLoadingUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string txtErrorBtn {
            get {
                return ResourceManager.GetString("txtErrorBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        public static string txtErrorMessage {
            get {
                return ResourceManager.GetString("txtErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string txtErrorTitle {
            get {
                return ResourceManager.GetString("txtErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string txtLearningSetCategory {
            get {
                return ResourceManager.GetString("txtLearningSetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string txtMultNo {
            get {
                return ResourceManager.GetString("txtMultNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string txtMultOk {
            get {
                return ResourceManager.GetString("txtMultOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string txtMultResult {
            get {
                return ResourceManager.GetString("txtMultResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many hints: .
        /// </summary>
        public static string txtMultTooManyHints {
            get {
                return ResourceManager.GetString("txtMultTooManyHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hints advice.
        /// </summary>
        public static string txtMultTooManyHintsTitle {
            get {
                return ResourceManager.GetString("txtMultTooManyHintsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string txtMultTotal {
            get {
                return ResourceManager.GetString("txtMultTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated word.
        /// </summary>
        public static string txtRandomLearningWord {
            get {
                return ResourceManager.GetString("txtRandomLearningWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string txtTitleConfiguation {
            get {
                return ResourceManager.GetString("txtTitleConfiguation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictation.
        /// </summary>
        public static string txtTitleDictation {
            get {
                return ResourceManager.GetString("txtTitleDictation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math operations.
        /// </summary>
        public static string txtTitleMathOps {
            get {
                return ResourceManager.GetString("txtTitleMathOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English words.
        /// </summary>
        public static string txtTitleWording {
            get {
                return ResourceManager.GetString("txtTitleWording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been saved to my documents.
        /// </summary>
        public static string txtUserDataLoaded {
            get {
                return ResourceManager.GetString("txtUserDataLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data has been uploaded.
        /// </summary>
        public static string txtUserDataNoDataUploaded {
            get {
                return ResourceManager.GetString("txtUserDataNoDataUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to overwrite your data?.
        /// </summary>
        public static string txtUserDataPrompt {
            get {
                return ResourceManager.GetString("txtUserDataPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to restart application.
        /// </summary>
        public static string txtUserDataUpdated {
            get {
                return ResourceManager.GetString("txtUserDataUpdated", resourceCulture);
            }
        }
    }
}
