//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiplicationTable.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiplicationTable.Resx.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string btnCheck {
            get {
                return ResourceManager.GetString("btnCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say it.
        /// </summary>
        internal static string btnSay {
            get {
                return ResourceManager.GetString("btnSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        internal static string btnShuffle {
            get {
                return ResourceManager.GetString("btnShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        internal static string btnTest {
            get {
                return ResourceManager.GetString("btnTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAD.
        /// </summary>
        internal static string txtDictBad {
            get {
                return ResourceManager.GetString("txtDictBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all answers selected.
        /// </summary>
        internal static string txtDictErrorNotAllAnsweres {
            get {
                return ResourceManager.GetString("txtDictErrorNotAllAnsweres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer all questions.
        /// </summary>
        internal static string txtDictErrorNotAllAnswersTitle {
            get {
                return ResourceManager.GetString("txtDictErrorNotAllAnswersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string txtDictOk {
            get {
                return ResourceManager.GetString("txtDictOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hurra!!!.
        /// </summary>
        internal static string txtDictSuccessMesssage {
            get {
                return ResourceManager.GetString("txtDictSuccessMesssage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRAVO.
        /// </summary>
        internal static string txtDictSuccessTitle {
            get {
                return ResourceManager.GetString("txtDictSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUM.
        /// </summary>
        internal static string txtDictSum {
            get {
                return ResourceManager.GetString("txtDictSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string txtErrorBtn {
            get {
                return ResourceManager.GetString("txtErrorBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string txtErrorMessage {
            get {
                return ResourceManager.GetString("txtErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string txtErrorTitle {
            get {
                return ResourceManager.GetString("txtErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string txtMultNo {
            get {
                return ResourceManager.GetString("txtMultNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string txtMultOk {
            get {
                return ResourceManager.GetString("txtMultOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string txtMultResult {
            get {
                return ResourceManager.GetString("txtMultResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many hints: .
        /// </summary>
        internal static string txtMultTooManyHints {
            get {
                return ResourceManager.GetString("txtMultTooManyHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hints advice.
        /// </summary>
        internal static string txtMultTooManyHintsTitle {
            get {
                return ResourceManager.GetString("txtMultTooManyHintsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string txtMultTotal {
            get {
                return ResourceManager.GetString("txtMultTotal", resourceCulture);
            }
        }
    }
}
